### ISSUE TITLE
ex6b.pl

### ISSUE THREAD

**Issue by gdbsm** [mmcpininga/ex6b-grupo05#6]
O que está acontecendo é que existem muitas possibilidades para serem testadas ate o prolog chegar no resultado, então podemos melhorar a função geracao2, para diminuir as possibilidades a serem testadas nesse caso, eu testei colocando as 38 entregas no primeiro horário e as 54 casas no terceiro horário, pois temos certeza que isso ocorreu e consegui um resultado(por volta de 15 segundos), mas estava errado, então modifiquei algumas dicas na regra solucao, mas não consegui obter o resultado correto. Logo, podemos tentar melhorar ainda mais a regra geracao2 e algumas dicas na solucao.

**Comment by rspds** [comment]
Ok

**Comment by mmcpininga** [comment]
isso! Eu sempre achei que tava funcionando, mas o problema é que não encontrava a solução. Mas acho que gente mesmo melhorando a geracao2 não vai encontrar o resultado certo pq falta dica. Eu fiz isso também... modifiquei a geracao2 para diminuir as possibilidades...se colocar você colocar entre as dicas onde é 'lagoa' e onde é 'estiva', funciona certinho.

**Comment by rspds** [comment]
sim na geracao2 poderiamos melhorar o desempenho do programa, conforme verifiquei

**Comment by mmcpininga** [comment]
As dicas foram modificadas da linha 38 até a linha 48 em conformidade com o desafio de lógica. Anteriormente as dicas não estavam completas, agora atendem-se os requisitos.

**Comment by rspds** [comment]
acreditei q o problema para nao dar solução seria o "tudo_dif" e/ou suas ramificações pois quando retirei ele o programa deu soluções, contudo com já descobriram, entao blz

**Comment by dfda** [comment]
Retirei o "tudo`_dif" no develop e master galera.

**Comment by Uiusu** [comment]
Encontrei uns erros nas linhas 28-29, elas ainda tavam interligadas com o "tudo_dif" que foi retirado. Agora ta tudo ok.

**Comment by JulianeRMC** [comment]
Achei alguns erros no comentário da linha 30 e alterei para a forma correta.

**Comment by rspds** [comment]
Visto que resolvemos todos os bugs, fecharei os issues abertos.

**Comment by mmcpininga** [comment]
O programa está funcionando corretamente, no entanto é importante ressaltar que a solução demora cerca de 20 minutos dependendo do processador.

**Comment by rspds** [comment]
Devido a um processamento demorado, reabri esse issues para informar que, como ainda temos tempo, trabalhemos nele afim de aperfeiçoá-lo. Acredito q o problema de processamento está na relação geracao <-> dif(devido ao backtracking). Espero ainda hj mandar minhas ideias em código.

**Comment by mmcpininga** [comment]
O tempo de processamento melhora bastante se  modificarmos apenas as posições do geração () e do dif () pois, como visto em sala, a posição dos comandos é muito importante!

**Comment by rspds** [comment]
Trabalhei nele analisando o q foi dado em sala, na relação geracao e dif. Apos alternar o geracao e o dif o programa reduziu de cerca de 20 mim para 10 segundos. 
Também adicionei um start pra melhorar a vida de quem for executar o programa. Criei alguns fatos "tempo" para colocar a hora real do carteiro( e não ficar tempo 1, 2, 3, 4, 5). 
A resposta do programa eu coloquei em uma frase, uma vez q exitem diferentes números indicando casa, entregas e tempo. E, além disso, facilitar a vida do professor pq foram diferentes desafios para os grupos criados.
